language: java

sudo: false
install: true

os: linux
dist: trusty
jdk: oraclejdk11


addons:
  sonarcloud:
    organization: "thiagobfim"
    token:
      secure: "m8A6sKjsPHuhTjBo97RDNICczdkaIgb7s52QNZ9oxTADV8rad7mFA4dpP5pneJ3Gk2uhqTyxpuIQ1sr9ijqQTjj1apgDWILi1G5teIny+y5h04nShKuVVHU8rlc9/ODT3DDWEXvkJQ1TVVUnD1d4ys7TLKdomBEWKQ4mkC6X82e87t1aWfNE2nsTmdKMwAUc7AQWCODpzsikSI0VFjPgq+kEyRWVHuovjwPrGSZ0MNOgYOUA4BTLM7EmA8wgERNECelqV7DCHiLqQHRzAZ/wtL9QH0mGfofkipiD+5iJhJ/yjvmHsJGn+kG2C5wKTd0hZnCxokBdf4FldihM5uFLxAzYpCKuAVsmV5TSm7GfZTG0FoqrCdqfnCddXPbIke1cGL0wtDnQ86Z9EzrS6TR3PX7EZ+IA5d/fOwGWhSubcA/N0OZQ2NL14j2TR6oEmze4PuxKcprhwBARxGbqh03KK6CnesvPSuLMh0m5zsNb1E+Uj9fTEO7Wo2MFKUB8uHXMebC/uLEi2E1gn/LyYQfZ9GZvuaT9XWu2d5+jiuTDpR1ddpXg5xnVic1m40q5058iXDJD2EUu0QwQWG+UyIXEGxNVYw9R3Xm7zjztv+z0jYjPKOFr/Blk8AvYQFaT8o5mcCTm1WIYgcY8whfVUJNRB5naHwt0F1qRYoySEBQXyk0="

before_install:
  - chmod +x mvnw

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ThiagoBfim_stocks

deploy:
  provider: heroku
  app: money-stocks
  api_key: $HEROKU_KEY


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
