language: java

os: linux
dist: trusty
jdk: oraclejdk11

before_install:
  - chmod +x mvnw

deploy:
  provider: heroku
  app: money-stocks
  api_key: $HEROKU_KEY


addons:
  sonarcloud:
    organization: "thiagobfim"
    token:
      secure: $SONAR_KEY

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
