language: java

os: linux
dist: trusty
jdk: oraclejdk8

jobs:
  include:
    - stage: "Build project"
      script:
        - ./mvn clean package

deploy:
  provider: heroku
  app: dio-cities-api-2
  api_key: $HEROKU_KEY
