
CREATE TABLE TB_STOCK (
  ID_STOCK      BIGSERIAL NOT NULL,
  COD_STOCK     varchar(6) NOT NULL,
  NU_DIVIDEND_YIELD  NUMERIC ,
  NU_MARKET_VALUE_BILLION  NUMERIC,
  NU_COMPANY_VALUE_BILLION  NUMERIC,
  NU_STAR  NUMERIC,
  CONSTRAINT PK_STOCK
    PRIMARY KEY (ID_STOCK)
);

ALTER TABLE TB_STOCK
 ADD  CONSTRAINT UK_COD_STOCK UNIQUE (COD_STOCK);

COMMENT ON TABLE TB_STOCK
  IS 'Table with info for stocks';

COMMENT ON COLUMN TB_STOCK.NU_STAR
  IS 'Ranges from 1 to 10 with 10 being excellent';
